### ISSUE TITLE
position, operator and name in ACSetTransformation prevents it from being natural

### ISSUE THREAD

**Issue by neonWhiteout** [AlgebraicJulia/StockFlow.jl#38]
Is there a way to map the names or positions to something else and still have naturality preserved?

**Comment by Xiaoyan-Li** [comment]
It seems currently the Catlab.jl does not support it.

**Comment by neonWhiteout** [comment]
This is expected, and shouldn't be changed.  ACSets are weird.

**Comment by neonWhiteout** [comment]
.
