### ISSUE TITLE
Stock and flow model syntax accepts non-existent stocks in flow definitions

### ISSUE THREAD

**Issue by Saityi** [AlgebraicJulia/StockFlow.jl#77]
### Issue

Currently this is accepted as a flow definition:

``` julia
:stocks
A
B
C

:flows
SDKLJFHSLKDJFHSLKDFHL => f(eq) => B
```

### Expectation

Flows that have source or target in a non-existent stock are rejected with a sensible error message.

**Comment by neonWhiteout** [comment]
This should be able to be closed too

**Comment by Saityi** [comment]
Addressed in #80
